Feature header headline
Jessemccallums/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2022-05-26 16:50 UTC by Jessemccallums

Project requirements
For this project, I should use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)

The 2 sections I need to build for this project are:

the toolbar (or header):
Toolbar

the headline section (right after the header):

2022-05-26 17:54 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Jessemccallums , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README is descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 17:54 UTC, leonardodiasb commented on index.html
> +    </main>
- [ ] Kindly add all the icons, buttons, and content present in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10). I can see that your design is very similar to Figma template 4 but there is more content in this section of the template. Please, stick to the template design as much as possible.
- [ ] Also make sure you are using the background images as in the template.

![image](https://user-images.githubusercontent.com/61919617/170545374-f1498332-d149-400e-b399-dda4a2288a80.png)
![image](https://user-images.githubusercontent.com/61919617/170545459-1207bfd5-7dd2-43d0-bccf-db3e7039022d.png)

2022-05-26 17:54 UTC, leonardodiasb commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
- [ ] Kindly make sure you are using all `<link>` references from [Roboto](https://fonts.google.com/specimen/Roboto) and your `'Roboto'` fonts are working. You can import them into the CSS file too.

2022-05-26 17:54 UTC, leonardodiasb commented on main.css
> +}
- [ ] Kindly use flexbox to layout this section as the Project Requirements mention.

2022-05-26 17:54 UTC, leonardodiasb commented on main.css
> +  fill: white;
- [ ] It is recommended to use RGB or hexadecimal values for colors in CSS. Kindly fix that.

2022-05-27 02:01 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
- [ ] I think it would be better to wrap all your images in the same folder to make your root directory cleaner. 
- [ ] I think it would be better, in your README.md file to relate the word 👤 **Author1** with your name, at line `31`.

_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 02:01 UTC, tresorsawasawa commented on index.html
> +    <title>Document</title>
- [ **OPTIONAL** ] I think it would be better if you rename your project's title to a meaningful one and more descriptive to make it more professional. **`e.g. : John's Portofolio`**

2022-05-27 02:01 UTC, tresorsawasawa commented on main.css
> +}
- [ **OPTIONAL**] I think it would be better to use the correct `font-size`, `line-height, and `font-weight` like the ones used at **Figma** so your project will match perfectly the [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A2346).

2022-05-27 06:54 UTC, merged