Desktop version
Jessemccallums/Portfolio-setup-and-mobile-version-skeleton pull request #6
Opened 2022-06-03 14:33 UTC by Jessemccallums

General requirements

+ I made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
+ I made sure that I used the correct ([Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
+ I made sure that I documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

Project requirements

+ I used media queries in my CSS file to make my desktop version look like the template I selected (Desktop: 768px or wider).

+ In order to lay out the elements on the page, I should use Grid and Flexbox.

+ I don't need to implement any functionality that requires JavaScript.

+ I must replicate the design as much as possible (e.g., font, colors, images, tests, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

*IMPORTANT NOTE* some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in Contact me or Get in touch sections). Please ignore this part of the design template and use only one input for the full name for all versions.

2022-06-03 18:02 UTC, Ismailco requested changes
### Hi @Jessemccallums,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 18:02 UTC, Ismailco commented on main.css
> +@media only screen and (min-width: 768px) {
- [ ] Please stick to the design as much as possible, you may change the font size and width of the element on the page so your design is as close to Figma design as possible, and kindly reduce the size of the envelope button in the nav bar

|Your design|Figma design|
|-|-|
|![Screenshot_20220603_184228](https://user-images.githubusercontent.com/25227022/171918655-e49b6cfa-73f5-4b1c-b8f8-25b44aa8d2fd.png)|![Screenshot_20220603_184416](https://user-images.githubusercontent.com/25227022/171918664-408d0eaf-f3a6-450e-920b-855b0a1b91d3.png)|

2022-06-03 18:02 UTC, Ismailco commented on main.css
> +@media only screen and (min-width: 768px) {
- [ ] The width and font size of the ```My recent work ``` headline is smaller on your design
- [ ] The ```hr``` is too much bold you can consider reducing it's size and width, please consider making the changes so your design is closer to the provided one

|Your design|Figma design|
|-|-|
|![Screenshot_20220603_184249](https://user-images.githubusercontent.com/25227022/171919297-56f5a8f2-4d27-4338-aca1-4811bb27f146.png)|![Screenshot_20220603_184400](https://user-images.githubusercontent.com/25227022/171919371-a748e2c5-5f08-4f43-bbeb-01ccf0c1d2b0.png)|

2022-06-03 18:02 UTC, Ismailco commented on main.css
> +  .maintextfooter {
- [ ] The footer is taking too much place on the desktop view, please consider reducing its size, so your design is as close to the provided one as possible

|Your design|Figma design|
|-|-|
|![Screenshot_20220603_184044](https://user-images.githubusercontent.com/25227022/171920169-d6eb7e61-9fea-42b6-8dcb-3cc0cd00bb5b.png)|![Screenshot_20220603_184340](https://user-images.githubusercontent.com/25227022/171920207-adb925f4-9190-4841-98ff-ff66959481e6.png)|

2022-06-03 18:02 UTC, Ismailco commented on main.css
> +.form-center-responsive {
- [ ] Please consider adding the same margin/padding on your page as in the Figma design, when you take advantage of the with space your design is more profession

![Screenshot_20220603_184044](https://user-images.githubusercontent.com/25227022/171920719-2a7dd1a1-dc80-4fed-bfb5-6c0fde38d687.png)

2022-06-03 18:24 UTC, Jessemccallums commented on main.css
> +  .maintextfooter {
Hi sir, this first picture is from the mobile version, It's different, I am working with desktop version.

2022-06-03 19:50 UTC, Ismailco commented on main.css
> +  .maintextfooter {
@Jessemccallums, Sorry I meant to add this image, here the issue is too much padding. you could see the difference between the two images. kindly reduce the padding at the bottom of the ```hr``` in the footer


|Your design|Figma design|
|-|-|
|![Screenshot_20220603_204839](https://user-images.githubusercontent.com/25227022/171939588-639bf0a7-dc96-443f-ab1b-0ad9190e46cd.png)|![Screenshot_20220603_184340](https://user-images.githubusercontent.com/25227022/171920207-adb925f4-9190-4841-98ff-ff66959481e6.png)|

2022-06-03 20:24 UTC, Jessemccallums commented on main.css
> +@media only screen and (min-width: 768px) {
Hi sir, you picked up the mobile version here, I will adjust my design to the Figma version, thank you in advance!

2022-06-04 05:14 UTC, descholar approved these changes
Hi @Jessemccallums ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-04 09:15 UTC, merged